using System;
using System.Data;
using System.Data.OleDb;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;

namespace PhysioProject2
{
	/// <summary>
	/// Interaction logic for Clients.xaml
	/// </summary>
	public partial class Clients : Page
    {

		OleDbConnection con;
		DataTable dt;

		public Clients()
        {
            InitializeComponent();
            this.DataContext = this;

			MoreInfo.Visibility = Visibility.Hidden;
			clientIDTxt.IsEnabled = false;

			con = new OleDbConnection();
			con.ConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0; Data Source=.\\PhysioDatabase.accdb"; //" + AppDomain.CurrentDomain.BaseDirectory + "
			BindGrid();
		}

		private void BindGrid()
		{
			OleDbCommand cmd = new OleDbCommand();
			if (con.State != ConnectionState.Open)
				con.Open();
			cmd.Connection = con;
			cmd.CommandText = "select * from ClientTableDB";
			OleDbDataAdapter da = new OleDbDataAdapter(cmd);
			dt = new DataTable();
			da.Fill(dt);
			ClientdataGrid.ItemsSource = dt.AsDataView();
		}

		private void SearchTxt_GotFocus(object sender, RoutedEventArgs e)
        {
            SearchTxt.Text = "";
        }


		private void addClient_Click(object sender, RoutedEventArgs e)
		{
			ClearAll();
			MoreInfo.Visibility = Visibility.Visible;
		}

		private void ClearAll()
		{
			clientIDTxt.Text = "";
			clientNameTxt.Text = "";
			clientSurnameTxt.Text = "";
			clientBirthdayTxt.Text = "";
			clientPhoneTxt.Text = "";
			clientDoctorTxt.Text = "";
			clientDiagnosisTxt.Text = "";
			MoreInfo.Visibility = Visibility.Hidden;
		}

		private void editClient_Click(object sender, RoutedEventArgs e)
		{
			if (ClientdataGrid.SelectedItems.Count > 0)
			{
				MoreInfo.Visibility = Visibility.Visible;
				DataRowView row = (DataRowView)ClientdataGrid.SelectedItems[0];
				clientIDTxt.Text = row["CID"].ToString();
				clientNameTxt.Text = row["Cname"].ToString();
				clientSurnameTxt.Text = row["CSurname"].ToString();
				clientBirthdayTxt.Text = row["Birthday"].ToString();
				clientPhoneTxt.Text = row["Telephone"].ToString();
				clientDoctorTxt.Text = row["Doctor"].ToString();
				clientDiagnosisTxt.Text = row["Diagnosis"].ToString();
			}
			else
			{
				MessageBox.Show("Παρακαλώ επιλέξτε ένα πελάτη από τη λίστα...");
			}
		}

		private void deleteClient_Click(object sender, RoutedEventArgs e)
		{
			if (ClientdataGrid.SelectedItems.Count > 0)
			{
				DataRowView row = (DataRowView)ClientdataGrid.SelectedItems[0];

				OleDbCommand cmd = new OleDbCommand();
				if (con.State != ConnectionState.Open)
					con.Open();
				cmd.Connection = con;
				cmd.CommandText = "delete from ClientTableDB where CID=" + row["CID"].ToString();
				cmd.ExecuteNonQuery();
				BindGrid();
				MessageBox.Show("Ο πελάτης διαγράφηκε με επιτυχία!!");
				ClearAll();
			}
			else
			{
				MessageBox.Show("Παρακαλώ επιλέξτε ένα πελάτη από τη λίστα...");
			}
		}

		private void ClientdataGrid_AutoGeneratedColumns(object sender, EventArgs e)
		{
			ClientdataGrid.Columns[3].Visibility = Visibility.Hidden;
			ClientdataGrid.Columns[4].Visibility = Visibility.Hidden;
			ClientdataGrid.Columns[5].Visibility = Visibility.Hidden;
			ClientdataGrid.Columns[6].Visibility = Visibility.Hidden;
		}

		private void save_Click(object sender, RoutedEventArgs e)
		{
			OleDbCommand cmd = new OleDbCommand();
			if (con.State != ConnectionState.Open)
				con.Open();
			cmd.Connection = con;

			if (clientNameTxt.Text != "")
			{
				if (clientIDTxt.Text == "")
				{
					cmd.CommandText = "insert into ClientTableDB(Cname,CSurname,Birthday,Telephone,Doctor,Diagnosis) Values('" + clientNameTxt.Text + "','" + clientSurnameTxt.Text + "','" + clientBirthdayTxt.Text + "','" + clientPhoneTxt.Text + "','" + clientDoctorTxt.Text + "','" + clientDiagnosisTxt.Text + "')";
					cmd.ExecuteNonQuery();
					BindGrid();
					MessageBox.Show("Ο νέος πελάτης προστέθηκε με επιτυχία!!");
					ClearAll();
				}
				else
				{
					cmd.CommandText = "update ClientTableDB set Cname='" + clientNameTxt.Text + "',CSurname='" + clientSurnameTxt.Text + "',Birthday='" + clientBirthdayTxt.Text + "',Telephone='" + clientPhoneTxt.Text + "',Doctor='" + clientDoctorTxt.Text + "',Diagnosis='" + clientDiagnosisTxt.Text + "' where CID=" + clientIDTxt.Text;
					cmd.ExecuteNonQuery();
					BindGrid();
					MessageBox.Show("Οι αλλαγές έγιναν με επιτυχία!!");
					ClearAll();
				}
			}
			else
			{
				MessageBox.Show("Παρακαλώ προσθέστε όνομα πελάτη.......");
			}
		}

		private void SearchTxt_TextChanged(object sender, TextChangedEventArgs e)
		{
			DataView dv = new DataView(dt);
			dv.RowFilter = string.Format("CSurname LIKE '{0}*'", SearchTxt.Text);
			ClientdataGrid.ItemsSource = dv;
		}
	}
}
